version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "4530:3000"
    restart: unless-stopped 
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "4000:80"       # nginx serving frontend on 80 inside container
    environment:
      - NODE_ENV=production