[build]
  command = "cd core && npm install && npm run build && cd ../frontend && npm install && npm run build && cd .."
  publish = "frontend/build"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
